/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import componentes.BotonRender;
import componentes.ButtonEditor;
import control.BotonListener;
import control.Control;
import control.Mediador;
import entidades.Producto;
import entidades.TipoComida;
import static enums.TiposComanda.CERRADA;
import static enums.TiposComanda.ELIMINADA;
import static enums.TiposComanda.MESA;
import static enums.TiposComanda.PEDIDO;
import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zaurus
 */
public class FrmAdministrarProductos extends javax.swing.JFrame {


    /**
     * Creates new form FrmAdministrarProductos
     */
    public FrmAdministrarProductos() {
        initComponents();
        
        Mediador.control.asignarFrmAdministrarProductos(this);
        cargarPantalla();
        lblPrecio.setText("Precio x Kilo");

        
    }
 
    public void cargarPantalla()
    {
        
        Mediador.control.cargarTablaProductos();
        tblProductos.setRowHeight(40);
        tblProductos.setBackground(Color.decode("#CB5F1D"));
    }
    public String getNombreFiltro()
    {
        return txtBuscarProducto.getText();
    }
    public JTable getTabla()
    {
        return tblProductos;
    }
    public void editar(Producto producto)
    {
        txtNombre.setText(producto.getNombre());
        txtPrecio.setText(""+producto.getPrecio());
        if(producto.getTipo() == TipoComida.COMIDA)
        {
            cbxTipo.setSelectedIndex(0);
        }else{
            cbxTipo.setSelectedIndex(1);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        pnlRegistro = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarProducto = new javax.swing.JButton();
        pnlProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        pnlOperaciones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 95, 29), 3));
        pnlFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlFondo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        pnlTitulo.setBackground(new java.awt.Color(203, 95, 29));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pnlTitulo.setMaximumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Productos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 298, 50, 319);
        pnlTitulo.add(lblTitulo, gridBagConstraints);

        pnlFondo.add(pnlTitulo);

        pnlOpciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpciones.setMaximumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setMinimumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setPreferredSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setLayout(new java.awt.GridLayout(1, 0));

        pnlRegistro.setBackground(new java.awt.Color(255, 255, 255));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(203, 95, 29));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo Alimento");
        lblTipo.setToolTipText("");
        lblTipo.setPreferredSize(new java.awt.Dimension(200, 27));
        lblTipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblTipo);

        cbxTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxTipo.setForeground(new java.awt.Color(203, 95, 29));
        cbxTipo.setMaximumRowCount(3);
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida" }));
        cbxTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 95, 29), 2, true));
        cbxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxTipo.setMaximumSize(new java.awt.Dimension(250, 50));
        cbxTipo.setMinimumSize(new java.awt.Dimension(250, 50));
        cbxTipo.setPreferredSize(new java.awt.Dimension(250, 40));
        cbxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoItemStateChanged(evt);
            }
        });
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        pnlRegistro.add(cbxTipo);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(203, 95, 29));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("");
        lblNombre.setPreferredSize(new java.awt.Dimension(200, 27));
        lblNombre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblNombre);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(203, 95, 29));
        txtNombre.setPreferredSize(new java.awt.Dimension(250, 40));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        pnlRegistro.add(txtNombre);

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(203, 95, 29));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio x ");
        lblPrecio.setToolTipText("");
        lblPrecio.setPreferredSize(new java.awt.Dimension(200, 27));
        lblPrecio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblPrecio);

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(203, 95, 29));
        txtPrecio.setPreferredSize(new java.awt.Dimension(250, 40));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        pnlRegistro.add(txtPrecio);

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlRegistro.add(jSeparator1);

        btnAgregarProducto.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Registrar Producto");
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.setMaximumSize(new java.awt.Dimension(170, 50));
        btnAgregarProducto.setMinimumSize(new java.awt.Dimension(170, 50));
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(170, 40));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        pnlRegistro.add(btnAgregarProducto);

        pnlOpciones.add(pnlRegistro);

        pnlProductos.setLayout(new javax.swing.BoxLayout(pnlProductos, javax.swing.BoxLayout.Y_AXIS));

        tblProductos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tipo", "Nombre", "Precio", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductos.setFocusable(false);
        jScrollPane1.setViewportView(tblProductos);
        if (tblProductos.getColumnModel().getColumnCount() > 0) {
            tblProductos.getColumnModel().getColumn(1).setMinWidth(100);
            tblProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblProductos.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        pnlProductos.add(jScrollPane1);

        jPanel1.setMaximumSize(new java.awt.Dimension(355, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(355, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(355, 40));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 8));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscar.setText("Buscar:");
        jPanel1.add(lblBuscar);

        txtBuscarProducto.setMaximumSize(new java.awt.Dimension(280, 25));
        txtBuscarProducto.setMinimumSize(new java.awt.Dimension(280, 25));
        txtBuscarProducto.setPreferredSize(new java.awt.Dimension(280, 25));
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarProducto);

        pnlProductos.add(jPanel1);

        pnlOpciones.add(pnlProductos);

        pnlFondo.add(pnlOpciones);

        pnlOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(203, 95, 29)));
        pnlOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setPreferredSize(new java.awt.Dimension(710, 130));
        pnlOperaciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 80, 45));

        btnRegresar.setBackground(new java.awt.Color(203, 95, 29));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setMaximumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setMinimumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setPreferredSize(new java.awt.Dimension(170, 60));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnRegresar);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_cerdito.png"))); // NOI18N
        pnlOperaciones.add(jLabel1);

        pnlFondo.add(pnlOperaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Mediador.cerrarFrmProductos();
        Mediador.abrirFrmPrincipal();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void cbxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoItemStateChanged

    }//GEN-LAST:event_cbxTipoItemStateChanged

    private void limpiarFormulario() {
        txtNombre.setText("");
        txtPrecio.setText("");
        txtBuscarProducto.setText("");
    }

    private Producto extraerDatos() {
        if (!validarDatos()) {
            return null;
        }

        TipoComida tipoComida;
        if (cbxTipo.getSelectedItem().toString().equals("Comida")) {
            tipoComida = TipoComida.COMIDA;
        } else {
            tipoComida = TipoComida.BEBIDA;
        }

        String nombre = txtNombre.getText().trim();
        float precio = Float.parseFloat(txtPrecio.getText().trim());

        Producto productoAGuardar = new Producto(tipoComida, nombre, precio);
        return productoAGuardar;
    }

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        String tipoSeleccionado = (String) cbxTipo.getSelectedItem();
    
        switch (tipoSeleccionado) {
            case "Comida":
                lblPrecio.setText("Precio x Kilo");
                break;
            case "Bebida":
                lblPrecio.setText("Precio x Unidad");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        Producto producto = extraerDatos();
        if (producto != null) {
            Producto productoRegistrado = Mediador.control.registrarProducto(producto);
            if (productoRegistrado == null) {
                producto.setEstado(true);
                producto.setId(Mediador.control.consultarProducto(producto.getNombre()).getId()); 
                Mediador.control.modificarProducto(producto);
                limpiarFormulario();
                cargarPantalla();
            } else {
                limpiarFormulario();
                cargarPantalla();
                Mediador.mostrarOptionPaneExito(this, "Producto agregado con éxito");
                
            }
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        String texto = txtNombre.getText();
        if (texto.length() >= 99) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == '.')) {
            evt.consume();
        }
        if (c == '.' && txtPrecio.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        Mediador.control.cargarTablaProductos();
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private boolean validarDatos() {
        TipoComida tipoComida;
        if (cbxTipo.getSelectedItem().toString().equals("Comida")) {
            tipoComida = TipoComida.COMIDA;
        } else {
            tipoComida = TipoComida.BEBIDA;
        }

        String nombre = txtNombre.getText().trim();
        String precioTexto = txtPrecio.getText().trim();

        if (tipoComida == null) {
            Mediador.mostrarOptionPaneError(this, "Por favor, seleccione un tipo de comida");
            return false;
        }

        if (nombre.isEmpty()) {
            Mediador.mostrarOptionPaneError(this, "Por favor, ingrese un nombre para el producto");
            return false;
        }

        if (nombre.length() > 99) {
            Mediador.mostrarOptionPaneError(this, "El nombre del producto no puede exceder los 99 caracteres");
            return false;
        }

        float precio;
        try {
            precio = Float.parseFloat(precioTexto);
            if (precio <= 0) {
                throw new NumberFormatException();
            }
            if (precio > Float.MAX_VALUE) {
                Mediador.mostrarOptionPaneError(this, "El precio del producto es demasiado grande");
                return false;
            }
        } catch (NumberFormatException e) {
            Mediador.mostrarOptionPaneError(this, "Por favor, ingrese un precio válido para el producto");
            return false;
        }

        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlOperaciones;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
