/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Zaurus
 */
public class FrmAdministrarProductos extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrarProductos
     */
    public FrmAdministrarProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        pnlRegistro = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregarProducto = new javax.swing.JButton();
        pnlProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComandas = new javax.swing.JTable();
        tfBuscar = new javax.swing.JTextField();
        pnlOperaciones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEliminadas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 95, 29), 3));
        pnlFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlFondo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        pnlTitulo.setBackground(new java.awt.Color(203, 95, 29));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pnlTitulo.setMaximumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Productos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 298, 50, 319);
        pnlTitulo.add(lblTitulo, gridBagConstraints);

        pnlFondo.add(pnlTitulo);

        pnlOpciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpciones.setMaximumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setMinimumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setPreferredSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setLayout(new java.awt.GridLayout());

        pnlRegistro.setBackground(new java.awt.Color(255, 255, 255));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(203, 95, 29));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo de Comanda");
        lblTipo.setToolTipText("");
        lblTipo.setPreferredSize(new java.awt.Dimension(200, 27));
        lblTipo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblTipo);

        cbxTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbxTipo.setForeground(new java.awt.Color(203, 95, 29));
        cbxTipo.setMaximumRowCount(3);
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pedido", "Mesa", "Express" }));
        cbxTipo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 95, 29), 2, true));
        cbxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxTipo.setMaximumSize(new java.awt.Dimension(250, 50));
        cbxTipo.setMinimumSize(new java.awt.Dimension(250, 50));
        cbxTipo.setPreferredSize(new java.awt.Dimension(250, 40));
        cbxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoItemStateChanged(evt);
            }
        });
        cbxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoActionPerformed(evt);
            }
        });
        pnlRegistro.add(cbxTipo);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(203, 95, 29));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("");
        lblNombre.setPreferredSize(new java.awt.Dimension(200, 27));
        lblNombre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblNombre);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(203, 95, 29));
        txtNombre.setPreferredSize(new java.awt.Dimension(250, 40));
        pnlRegistro.add(txtNombre);

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblPrecio.setForeground(new java.awt.Color(203, 95, 29));
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecio.setText("Precio x ");
        lblPrecio.setToolTipText("");
        lblPrecio.setPreferredSize(new java.awt.Dimension(200, 27));
        lblPrecio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlRegistro.add(lblPrecio);

        txtPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(203, 95, 29));
        txtPrecio.setPreferredSize(new java.awt.Dimension(250, 40));
        pnlRegistro.add(txtPrecio);

        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        pnlRegistro.add(jSeparator1);

        btnAgregarProducto.setBackground(new java.awt.Color(51, 153, 0));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarProducto.setMaximumSize(new java.awt.Dimension(170, 50));
        btnAgregarProducto.setMinimumSize(new java.awt.Dimension(170, 50));
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(170, 40));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        pnlRegistro.add(btnAgregarProducto);

        pnlOpciones.add(pnlRegistro);

        pnlProductos.setLayout(new javax.swing.BoxLayout(pnlProductos, javax.swing.BoxLayout.Y_AXIS));

        tblComandas.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        tblComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComandas.setFocusable(false);
        jScrollPane1.setViewportView(tblComandas);

        pnlProductos.add(jScrollPane1);

        tfBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfBuscar.setForeground(new java.awt.Color(203, 95, 29));
        tfBuscar.setText("Buscar");
        tfBuscar.setPreferredSize(new java.awt.Dimension(64, 40));
        pnlProductos.add(tfBuscar);

        pnlOpciones.add(pnlProductos);

        pnlFondo.add(pnlOpciones);

        pnlOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(203, 95, 29)));
        pnlOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setPreferredSize(new java.awt.Dimension(710, 130));
        pnlOperaciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 50));

        btnRegresar.setBackground(new java.awt.Color(203, 95, 29));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setMaximumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setMinimumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setPreferredSize(new java.awt.Dimension(170, 60));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnRegresar);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_cerdito.png"))); // NOI18N
        pnlOperaciones.add(jLabel1);

        btnEliminadas.setBackground(new java.awt.Color(203, 95, 29));
        btnEliminadas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminadas.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminadas.setContentAreaFilled(false);
        btnEliminadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminadas.setEnabled(false);
        btnEliminadas.setMaximumSize(new java.awt.Dimension(170, 60));
        btnEliminadas.setMinimumSize(new java.awt.Dimension(170, 60));
        btnEliminadas.setPreferredSize(new java.awt.Dimension(170, 60));
        btnEliminadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminadasActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnEliminadas);

        pnlFondo.add(pnlOperaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminadasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEliminadasActionPerformed

    private void cbxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoItemStateChanged

    }//GEN-LAST:event_cbxTipoItemStateChanged

    private void cbxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTipoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed

    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEliminadas;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlOperaciones;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JPanel pnlRegistro;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTable tblComandas;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
