/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Mediador;
import enums.TiposComanda;
import static enums.TiposComanda.CERRADA;
import static enums.TiposComanda.MESA;
import static enums.TiposComanda.PEDIDO;

/**
 *
 * @author Ángel Valenzuela
 */
public class FrmComandas extends javax.swing.JFrame {

    /**
     * Creates new form FrmComandas
     */
    public FrmComandas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlFondo = new javax.swing.JPanel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        btnMesas = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnCerradas = new javax.swing.JButton();
        pnlOperaciones = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCrearComanda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 607));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 95, 29), 3));
        pnlFondo.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlFondo.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlFondo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        pnlTitulo.setBackground(new java.awt.Color(203, 95, 29));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        pnlTitulo.setMaximumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(710, 100));
        pnlTitulo.setLayout(new java.awt.GridBagLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Comandas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 298, 50, 319);
        pnlTitulo.add(lblTitulo, gridBagConstraints);

        pnlFondo.add(pnlTitulo);

        pnlOpciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOpciones.setMaximumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setMinimumSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setPreferredSize(new java.awt.Dimension(710, 300));
        pnlOpciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 50));

        btnMesas.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btnMesas.setForeground(new java.awt.Color(255, 255, 255));
        btnMesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_mesas.png"))); // NOI18N
        btnMesas.setText("Mesas");
        btnMesas.setBorderPainted(false);
        btnMesas.setContentAreaFilled(false);
        btnMesas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMesas.setMaximumSize(new java.awt.Dimension(200, 200));
        btnMesas.setMinimumSize(new java.awt.Dimension(200, 200));
        btnMesas.setOpaque(true);
        btnMesas.setPreferredSize(new java.awt.Dimension(200, 200));
        btnMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnMesas);

        btnPedidos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_pedidos.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedidos.setMaximumSize(new java.awt.Dimension(200, 200));
        btnPedidos.setMinimumSize(new java.awt.Dimension(200, 200));
        btnPedidos.setPreferredSize(new java.awt.Dimension(200, 200));
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnPedidos);

        btnCerradas.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btnCerradas.setForeground(new java.awt.Color(255, 255, 255));
        btnCerradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_cerradas.png"))); // NOI18N
        btnCerradas.setText("Cerradas");
        btnCerradas.setBorder(null);
        btnCerradas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerradas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerradas.setMaximumSize(new java.awt.Dimension(200, 200));
        btnCerradas.setMinimumSize(new java.awt.Dimension(200, 200));
        btnCerradas.setPreferredSize(new java.awt.Dimension(200, 200));
        btnCerradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerradasActionPerformed(evt);
            }
        });
        pnlOpciones.add(btnCerradas);

        pnlFondo.add(pnlOpciones);

        pnlOperaciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 0, 0, new java.awt.Color(203, 95, 29)));
        pnlOperaciones.setForeground(new java.awt.Color(255, 255, 255));
        pnlOperaciones.setPreferredSize(new java.awt.Dimension(710, 130));
        pnlOperaciones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 50));

        btnRegresar.setBackground(new java.awt.Color(203, 95, 29));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setMaximumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setMinimumSize(new java.awt.Dimension(170, 60));
        btnRegresar.setPreferredSize(new java.awt.Dimension(170, 60));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnRegresar);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_comandas/img_cerdito.png"))); // NOI18N
        pnlOperaciones.add(jLabel1);

        btnCrearComanda.setBackground(new java.awt.Color(203, 95, 29));
        btnCrearComanda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearComanda.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearComanda.setText("Crear Comanda");
        btnCrearComanda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearComanda.setMaximumSize(new java.awt.Dimension(170, 60));
        btnCrearComanda.setMinimumSize(new java.awt.Dimension(170, 60));
        btnCrearComanda.setPreferredSize(new java.awt.Dimension(170, 60));
        btnCrearComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearComandaActionPerformed(evt);
            }
        });
        pnlOperaciones.add(btnCrearComanda);

        pnlFondo.add(pnlOperaciones);

        getContentPane().add(pnlFondo);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComandaActionPerformed
        this.setVisible(false);
        Mediador.abrirFrmRegistroComanda();
        
    }//GEN-LAST:event_btnCrearComandaActionPerformed

    private void btnMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasActionPerformed
        this.dispose();
        Mediador.abrirFrmAdministrarComanda(MESA);
    }//GEN-LAST:event_btnMesasActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        this.dispose();
        Mediador.abrirFrmAdministrarComanda(PEDIDO);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnCerradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerradasActionPerformed
        this.dispose();
        Mediador.abrirFrmAdministrarComanda(CERRADA);
    }//GEN-LAST:event_btnCerradasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Mediador.abrirFrmPrincipal();
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerradas;
    private javax.swing.JButton btnCrearComanda;
    private javax.swing.JButton btnMesas;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlOperaciones;
    private javax.swing.JPanel pnlTitulo;
    // End of variables declaration//GEN-END:variables
}
