/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import control.Mediador;

/**
 *
 * @author Angel
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlInteracciones = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        btnComandas = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnReporteVentas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setBackground(new java.awt.Color(203, 95, 29));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(800, 600));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlPrincipal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otros/logo_cj.png"))); // NOI18N
        pnlPrincipal.add(jLabel1);

        pnlInteracciones.setBackground(new java.awt.Color(255, 255, 255));
        pnlInteracciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        pnlInteracciones.setMaximumSize(new java.awt.Dimension(300, 330));
        pnlInteracciones.setMinimumSize(new java.awt.Dimension(300, 330));
        pnlInteracciones.setPreferredSize(new java.awt.Dimension(300, 330));
        pnlInteracciones.setLayout(new java.awt.GridBagLayout());

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(203, 95, 29));
        lblTipo.setText("CJ System");
        lblTipo.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlInteracciones.add(lblTipo, gridBagConstraints);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));
        pnlBotones.setMaximumSize(new java.awt.Dimension(275, 240));
        pnlBotones.setMinimumSize(new java.awt.Dimension(275, 240));
        pnlBotones.setPreferredSize(new java.awt.Dimension(275, 240));
        pnlBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btnComandas.setBackground(new java.awt.Color(255, 255, 255));
        btnComandas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnComandas.setForeground(new java.awt.Color(203, 95, 29));
        btnComandas.setText("Comandas");
        btnComandas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 95, 29), 5, true));
        btnComandas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComandas.setMaximumSize(new java.awt.Dimension(200, 60));
        btnComandas.setMinimumSize(new java.awt.Dimension(200, 60));
        btnComandas.setPreferredSize(new java.awt.Dimension(200, 60));
        btnComandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandasActionPerformed(evt);
            }
        });
        pnlBotones.add(btnComandas);

        btnProductos.setBackground(new java.awt.Color(255, 255, 255));
        btnProductos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(203, 95, 29));
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 95, 29), 5));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductos.setMaximumSize(new java.awt.Dimension(200, 60));
        btnProductos.setMinimumSize(new java.awt.Dimension(200, 60));
        btnProductos.setPreferredSize(new java.awt.Dimension(200, 60));
        pnlBotones.add(btnProductos);

        btnReporteVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnReporteVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReporteVentas.setForeground(new java.awt.Color(203, 95, 29));
        btnReporteVentas.setText("Reporte de ventas");
        btnReporteVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(203, 95, 29), 5, true));
        btnReporteVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteVentas.setMaximumSize(new java.awt.Dimension(200, 60));
        btnReporteVentas.setMinimumSize(new java.awt.Dimension(200, 60));
        btnReporteVentas.setPreferredSize(new java.awt.Dimension(200, 60));
        btnReporteVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteVentasActionPerformed(evt);
            }
        });
        pnlBotones.add(btnReporteVentas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 0, 0);
        pnlInteracciones.add(pnlBotones, gridBagConstraints);

        jSeparator1.setBackground(new java.awt.Color(203, 95, 29));
        jSeparator1.setForeground(new java.awt.Color(203, 95, 29));
        jSeparator1.setMaximumSize(new java.awt.Dimension(300, 3));
        jSeparator1.setMinimumSize(new java.awt.Dimension(300, 3));
        jSeparator1.setPreferredSize(new java.awt.Dimension(300, 3));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 3, 0);
        pnlInteracciones.add(jSeparator1, gridBagConstraints);

        pnlPrincipal.add(pnlInteracciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandasActionPerformed
        Mediador.abrirFrmComandas();
        dispose();
    }//GEN-LAST:event_btnComandasActionPerformed

    private void btnReporteVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteVentasActionPerformed
        Mediador.abrirFrmReporteVentas();
        dispose();
    }//GEN-LAST:event_btnReporteVentasActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComandas;
    private javax.swing.JButton btnCrearComanda;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresar1;
    private javax.swing.JButton btnReporteVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlInteracciones;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
