/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import enums.TiposComanda;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.JLabel;

/**
 *
 * @author Ángel Valenzuela
 */
public class PnlTipoComandas extends javax.swing.JPanel {

    /**
     * Creates new form PnlTipoComandas
     * @param tipoComanda
     */
    public PnlTipoComandas(int tipoComanda) {
        initComponents();
        actualizarPanel(tipoComanda);
    }
    
    public void actualizarPanel(int tipoComanda) {
        removeAll();

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(5, 5, 5, 5);

        switch (tipoComanda) {
            case TiposComanda.PEDIDO ->                 {
                    JLabel lblNombreCliente = new JLabel("Nombre del cliente");
                    add(lblNombreCliente, gbc);
                    JLabel lblDireccion = new JLabel("Dirección");
                    add(lblDireccion, gbc);
                }
            case TiposComanda.MESA ->                 {
                    JLabel lblDireccion = new JLabel("Dirección");
                    add(lblDireccion, gbc);
                }
            case TiposComanda.EXPRESS ->                 {
                    JLabel label = new JLabel("Contenido del Panel 3");
                    add(label, gbc);
                }
            default -> {
            }
        }

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
